version: "2"
services:
  tensorflow:
    image: tensorflow/tensorflow
    ports:
      - 80:8888
    volumes:
      - /home/vaayne/docker/tensorflow/jupyter:/root/.jupyter
      - /home/vaayne/docker/tensorflow/notebook:/notebook
    container_name: tensorflow

